name: Sonyliv Fetch and Upload Data

on:
  schedule:
    - cron: '*/20 * * * *' # Runs every 20 minutes
  push:
    branches:
      - main

jobs:
  fetch_and_upload:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.GH_TOKEN }} # Use the GitHub token for authentication

    - name: Remove existing files
      run: rm -f sonyliv.json sonyliv.m3u

    - name: Configure Git
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git remote set-url origin https://${{ secrets.GH_TOKEN }}@github.com/drmlive/sliv-live-events.git

    - name: Fetch data from APIs
      run: |
        curl -o sonyliv.json https://sliv-api.drmlive.au/
        curl -o sonyliv.m3u https://sliv-api.drmlive.au/sonyliv.m3u

    - name: Commit and push changes
      run: |
        git add sonyliv.json sonyliv.m3u
        git fetch origin main
        git reset --soft origin/main
        if git diff --cached --quiet; then
          echo "No changes to commit"
        else
          git commit -m "Fetch latest data"
          git push origin main
        fi
